apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: bhardwajcr7/devops-qr-code-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: LoadBalancer
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

